// ─────────────── نقش‌ها و دسترسی‌ها (RBAC) ───────────────
// نقش‌ها در ستون role جدول admin_users ذخیره می‌شوند.
// نقش ADMIN به عنوان نام قدیمی نگه داشته شده و مانند HOTEL_ADMIN رفتار می‌کند.
// Permission در دو لایه کنترل می‌شود: Backend (این فایل + middleware) و Frontend (نمایش منو/دکمه)

const ALL_PERMISSIONS = [
  "dashboard.view",
  "analytics.view",
  "reservations.view",
  "reservations.create",
  "reservations.update",
  "reservations.cancel",
  "rooms.view",
  "rooms.create",
  "rooms.update",
  "rooms.delete",
  "payments.view",
  "payments.manage",
  "refunds.view",
  "refunds.process",
  "refunds.confirm",
  "customers.view",
  "customers.update",
  "support.view",
  "support.reply",
  "notifications.send",
  "sms.send",
  "settings.view",
  "settings.update",
  "admins.view",
  "admins.manage",
  "audit_logs.view",
  "discounts.view",
  "discounts.manage",
  "reviews.view",
  "reviews.manage",
];

const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ADMIN: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "reservations.create",
    "reservations.update",
    "reservations.cancel",
    "rooms.view",
    "rooms.create",
    "rooms.update",
    "payments.view",
    "payments.manage",
    "refunds.view",
    "refunds.process",
    "refunds.confirm",
    "customers.view",
    "customers.update",
    "support.view",
    "support.reply",
    "notifications.send",
    "sms.send",
    "settings.view",
    "settings.update",
    "discounts.view",
    "discounts.manage",
    "reviews.view",
    "reviews.manage",
  ],
  MANAGER: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "reservations.create",
    "reservations.update",
    "reservations.cancel",
    "rooms.view",
    "rooms.create",
    "rooms.update",
    "payments.view",
    "payments.manage",
    "refunds.view",
    "refunds.process",
    "refunds.confirm",
    "customers.view",
    "customers.update",
    "support.view",
    "support.reply",
    "notifications.send",
    "sms.send",
    "settings.view",
    "discounts.view",
    "discounts.manage",
    "reviews.view",
    "reviews.manage",
  ],
  RESERVATION_MANAGER: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "reservations.create",
    "reservations.update",
    "reservations.cancel",
    "rooms.view",
    "customers.view",
    "support.view",
    "notifications.send",
  ],
  FINANCE_MANAGER: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "payments.view",
    "payments.manage",
    "refunds.view",
    "refunds.process",
    "refunds.confirm",
    "customers.view",
    "support.view",
  ],
  SUPPORT_ADMIN: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "customers.view",
    "customers.update",
    "support.view",
    "support.reply",
    "notifications.send",
  ],
  RECEPTIONIST: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "reservations.create",
    "reservations.update",
    "reservations.cancel",
    "rooms.view",
    "rooms.update",
    "customers.view",
    "customers.update",
    "support.view",
    "notifications.send",
    "payments.view",
  ],
  VIEWER: [
    "dashboard.view",
    "analytics.view",
    "reservations.view",
    "rooms.view",
    "payments.view",
    "customers.view",
    "support.view",
    "discounts.view",
    "reviews.view",
  ],
};

function roleHasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role];
  if (!perms) return false;
  if (perms.includes("*")) return true;
  return perms.includes(permission);
}

function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] || [];
}

// برچسب فارسی نقش‌ها برای نمایش در رابط کاربری
const ROLE_LABELS = {
  SUPER_ADMIN: "مدیر ارشد سیستم",
  ADMIN: "مدیر هتل",
  MANAGER: "مدیر ارشد هتل",
  RESERVATION_MANAGER: "مدیر رزرو",
  FINANCE_MANAGER: "مدیر مالی",
  SUPPORT_ADMIN: "مدیر پشتیبانی",
  RECEPTIONIST: "پذیرش",
  VIEWER: "ناظر (فقط مشاهده)",
};

module.exports = { ALL_PERMISSIONS, ROLE_PERMISSIONS, roleHasPermission, getRolePermissions, ROLE_LABELS };
